USE GRS_PRE;
drop table if exists `GRS_USERS_COMMON`;
CREATE TABLE GRS_USERS_COMMON
(
    user_id MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(64) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    registered_datetime DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL,
    last_login_datetime DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL,
    email_status TINYINT DEFAULT 0 NOT NULL,
    status TINYINT DEFAULT 0 NOT NULL,
    avatar VARCHAR(1024) DEFAULT NULL
);

drop table if exists `GRS_USERS_META`;
CREATE TABLE GRS_USERS_META
(
    umeta_id MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
    meta_key VARCHAR(255) DEFAULT NULL,
    meta_value LONGTEXT DEFAULT NULL,
    CONSTRAINT FK_USERS_COMMON_META FOREIGN KEY (user_id) REFERENCES GRS_USERS_COMMON(user_id)
);

PSN_USERS_META
(
  psn_user_id MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
  psn_user_name VARCHAR(30) NOT NULL,
  avatar_url VARCHAR(1024) DEFAULT NULL
  is_plus_uesr TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  psn_level SMALLINT(3) UNSIGNED NOT NULL DEFAULT 0,
  next_level SMALLINT(2) UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT FK_USERS_PSN FOREIGN KEY (user_id) REFERENCES GRS_USERS_COMMON(user_id)
)

GAME_PROGRESS
(
  game_prog_id MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
  game_id MEDIUMINT(10) UNSIGNED DEFAULT 0 NOT NULL,
  progress TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL,
  progress_platinum TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  progress_glod TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  progress_silver TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  progress_bronze TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  progress_point SMALLINT(4) UNSIGNED NOT NULL DEFAULT 0
)

TROPHY_PROGRESS
(
  trophy_prog_id MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
  game_id MEDIUMINT(10) UNSIGNED DEFAULT 0 NOT NULL,
  trophy_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
  trohpy_stamp TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL
)

GAME
(
  game_id MEDIUMINT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  psn_game_id VARCHAR(12),
  xbl_game_id VARCHAR(12),
  game_type TINYINT(2) DEFAULT 0 NOT NULL, --PS3:1, PSP:2, PSV:3, PS4:4, PSN:5, 360:6, X1:7, XBL:8
  game_title VARCHAR(1024)  NOT NULL,
  description VARCHAR(4096) NOT NULL,
  img_url VARCHAR(1024) DEFAULT NULL,
  trophy_platinum TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  trophy_gold TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  trophy_silver TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  trophy_bronze TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  trophy_point SMALLINT(4) UNSIGNED NOT NULL DEFAULT 0
)

TROPHY
(
    tid MEDIUMINT(12) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    game_id MEDIUMINT(12) UNSIGNED DEFAULT 0 NOT NULL,
    psn_trophy_id SMALLINT(3) NOT NULL DEFAULT 0,
    xbl_trophy_id SMALLINT(3) NOT NULL DEFAULT 0,
    trophy_type TINYINT(1), --PLATINUM:4, GOLD:3, SILVER:2, BRONZE:1
    trophy_point SMALLINT(4), --XBOX LIVE POINT
    trophy_title VARCHAR(1024) DEFAULT NULL,
    img_url VARCHAR(1024) DEFAULT NULL,
    description VARCHAR(4096) NOT NULL
)